### ISSUE TITLE
Error on benchmark: undefined symbol: json_parser_new

### ISSUE THREAD

**Issue by djunho** [lpereira/hardinfo#551] opened 2020-05-21 22:03 UTC
When I click on any benchmark in the application it closed unexpectedly. For example, clicking at "CPU Blowfish (single-thread)" returns the error.
The terminal log is:
```
$ hardinfo                                                                                                                                                 
Gtk-Message: 18:50:57.528: Failed to load module "canberra-gtk-module"
** (hardinfo:51970): CRITICAL **: 18:50:57.588: gail_notebook_real_remove_gtk: assertion 'obj' failed
** (hardinfo:51970): CRITICAL **: 18:50:57.588: gail_notebook_real_remove_gtk: assertion 'obj' failed
hardinfo: symbol lookup error: /usr/local/lib/hardinfo/modules/benchmark.so: undefined symbol: json_parser_new
```

To compile the application I ran:
```
sudo apt install libgtk2.0-dev libsoup2.4-dev libjson-glib-dev build-essential
git clone https://github.com/lpereira/hardinfo.git
cd hardinfo
mkdir build
cd build
cmake ..
make
```

Everything ran with success. But I still get that error when running.

I am using Ubuntu 20.04.

**Comment by bp0** [comment] 2020-05-25 01:42
Same for me.

**Comment by lpereira** [comment] 2020-05-25 17:02
I'm installing Ubuntu 20.04 on a VM here just to test this.  I can't reproduce on Debian 10.  I found and fixed an issue that could lead to this problem if the GTK+3 version was being built, but from the commands above that doesn't seem to be the case.

**Comment by lpereira** [comment] 2020-05-25 18:50
OK, this is reproducible. Let me figure out what's causing it

**Comment by lpereira** [comment] 2020-05-25 18:56
It should be fixed in `HEAD`, could you give it a try, @bp0  and @djunho?

**Comment by bp0** [comment] 2020-05-25 19:58
Seems to be fixed now.

**Comment by lpereira** [comment] 2020-05-25 20:35
Closing as fixed, then, thanks for confirming!

**Comment by StatusCode404** [comment] 2021-09-16 09:00
I'm getting this error and I'm on Master branch.
`$ sudo /usr/local/bin/hardinfo`
`/usr/local/bin/hardinfo: symbol lookup error: /usr/local/lib/hardinfo/modules/devices.so: undefined symbol: json_parser_new`

I basically did the same thing and followed instructions to the letter.  Made "build" folder then "cmake .." then "make" then "sudo make install"

I tried putting in a pkexec profile and running sudo and without sudo; all results to the same error above.

**Comment by lpereira** [comment] 2021-09-16 23:27
Reopened as it seems it's happening again.

**Comment by StatusCode404** [comment] 2021-09-27 09:01
Hi All, anyone have an idea how how to fix this?

**Comment by lpereira** [comment] 2021-09-27 16:32
Should be fixed; please rebuild from the `master` branch and report if it's working.

**Comment by StatusCode404** [comment] 2021-09-28 07:42
Thanks!  grabbing it now...

**Comment by StatusCode404** [comment] 2021-09-28 08:29
Works!
Thanks for fixing!  Sync with server benchmarks also works!

**Comment by lpereira** [comment] 2021-09-29 23:00
Closing as fixed, then. Thanks for confirming!

**Closed by lpereira** 2021-09-29 23:00 UTC
Labels: bug
