### ISSUE TITLE
USB Devices

### ISSUE THREAD

**Issue by Testato** [lpereira/hardinfo#32] opened 2016-05-21 15:17 UTC
the USB field is always empty, i tried on many different distribution.
Now i'm on a Kubuntu 16.04 64bit

Instead the terminal command report it
```
kubuntu@kubuntu-PC:~$ lsusb
Bus 002 Device 007: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
Bus 002 Device 006: ID 1d6b:0104 Linux Foundation Multifunction Composite Gadget
Bus 002 Device 005: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 002 Device 004: ID 04f3:0103 Elan Microelectronics Corp. ActiveJet K-2024 Multimedia Keyboard
Bus 002 Device 003: ID 046d:c050 Logitech, Inc. RX 250 Optical Mouse
Bus 002 Device 008: ID 058f:6387 Alcor Micro Corp. Flash Drive
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by lpereira** [comment] 2016-05-21 21:37
Thanks for reporting the bug!

This bug has been fixed in the version that's in this repository, but since a mainteinance release has not been officially made yet, no distributions have updated HardInfo. Feel free to uninstall the package from your distribution and compile yourself the newest version; if you need help building besides what's written in the README file, don't hesitate to reopen this ticket.

**Closed by lpereira** 2016-05-21 21:37 UTC

**Comment by mckaygerhard** [comment] 2016-05-27 15:54
@Testato u can use the dsc file of VenenuX as a dsc template to guide and rebuild using dget and dpkg-build.. but i dont use winbuntu so u must made some tune

http://venenuxrepo.fundacite-aragua.gob.ve/mskcommon/desktop/hardinfo/hardinfo_0.5.2pre-1.dsc

i confirmed that this issue was already fixed long time ago now

**Comment by Testato** [comment] 2016-05-27 16:49
thanks for the tips, but i can wait an official release.
you know when it comes out ?
